spam = ['cat','bat','rat','elephant']
print('slice from index 0 to 4')
print(spam[0:4])
print('slice from index 1 to 3')
print(spam[1:3])
print('slice from index 0 to the second to last index')
print(spam[0:-1])
print('slice from index 1 to end')
print(spam[1:])
print('print all with spam(:)')
print(spam[:])